const frame=document.querySelector('#demo'),status=document.querySelector('#status');
frame.onload=()=>{const window=frame.contentWindow;const ready=()=>{document.querySelector('#image').disabled=document.querySelector('#video').disabled=false;status.textContent='Ready. Fixtures enter the same File input handler as user-selected media. Use Estimate camera pose in the demo.'};
  if(window.document.documentElement.dataset.visualReady)ready();else window.addEventListener('visual-ready',ready,{once:true});
  const fetch=window.fetch.bind(window);window.fetch=(url,options)=>{if(['/api/uploads','/api/localize'].includes(String(url)))throw Error('Browser processing attempted a server inference request');return fetch(url,options)};
};frame.src='/';
async function load(name,type){const response=await fetch('/models/'+name);if(!response.ok)throw Error('Prepare the local browser test fixtures first.');const blob=await response.blob(),window=frame.contentWindow,transfer=new window.DataTransfer();transfer.items.add(new window.File([blob],name,{type}));const input=window.document.querySelector('#input');input.files=transfer.files;input.dispatchEvent(new window.Event('change',{bubbles:true}));status.textContent='Fixture loaded through the media input. Server inference requests are blocked by this check.'}
document.querySelector('#image').onclick=()=>load('test-input.png','image/png').catch(e=>status.textContent=String(e));
document.querySelector('#video').onclick=()=>load('test-video.mp4','video/mp4').catch(e=>status.textContent=String(e));
document.querySelector('#report').onclick=()=>{try{const d=frame.contentDocument,value=JSON.parse(d.querySelector('#details').textContent),f=value.observation;status.textContent=JSON.stringify({decision:f.decision,capture_time_ns:f.capture_time_ns,inliers:f.candidate_hypotheses?.filter(h=>h.accepted).map(h=>h.inliers),reprojection_rms_px:f.candidate_hypotheses?.filter(h=>h.accepted).map(h=>h.reprojection_rms_px),retrieval:f.retrieval,processing_ms:f.processing_ms,status:d.querySelector('#run-status').textContent},null,2)}catch(e){status.textContent=String(e)}};
