const frame=document.querySelector('#demo'),status=document.querySelector('#status'),report={};
const assert=(name,value)=>{if(!value)throw Error(name);report[name]=true;status.textContent=JSON.stringify(report,null,2)};
function until(window,predicate){return new Promise((resolve,reject)=>{const origin=new Error('UI wait started');let observer,timer;const check=()=>{if(!predicate())return;observer?.disconnect();clearTimeout(timer);resolve()};observer=new window.MutationObserver(check);observer.observe(window.document.documentElement,{subtree:true,childList:true,attributes:true,characterData:true});timer=setTimeout(()=>{observer.disconnect();reject(Error('UI condition timed out: '+origin.stack))},120000);check()})}
frame.onload=async()=>{const window=frame.contentWindow,d=window.document,$=id=>d.getElementById(id);try{
 await until(window,()=>d.documentElement.dataset.visualReady);const fetch=window.fetch.bind(window);window.fetch=(url,args)=>{if(['/api/uploads','/api/localize'].includes(String(url)))throw Error('Unexpected server inference');return fetch(url,args)};
 const load=async(name,type)=>{const transfer=new window.DataTransfer();transfer.items.add(new window.File([await(await fetch('/models/'+name)).blob()],name,{type}));$('input').files=transfer.files;$('input').dispatchEvent(new window.Event('change',{bubbles:true}));await until(window,()=>!$('locate').disabled)};
 $('region').value='new-jersey';$('region').dispatchEvent(new window.Event('change'));await until(window,()=>/prepared imagery|Verified offline package/.test($('pack-status').textContent));$('download').click();await until(window,()=>!$('download').disabled&&$('map-empty').hidden);
 await load('test-input.png','image/png');assert('image input previews locally',Boolean($('query').src));
 $('locate').click();await until(window,()=>/retrieval|reference features/i.test($('run-status').textContent));const count=Number($('map').dataset.frames);$('north').click();await until(window,()=>Number($('map').dataset.frames)>count);assert('camera moves during matching',$('map-label').textContent.includes('FREE CAMERA'));
 $('cancel').click();await until(window,()=>!$('locate').disabled);assert('cancel restores controls',$('cancel').disabled);
 $('locate').click();await until(window,()=>!$('locate').disabled);let image=JSON.parse($('details').textContent).observation;assert('image creates a geometric result',image.candidate_hypotheses.some(h=>h.accepted));report.image={decision:image.decision,processing_ms:image.processing_ms,execution:image.execution};
 await load('test-video.mp4','video/mp4');assert('video frame control available',!$('video-controls').hidden);$('frame-time').value=2;$('frame-time').dispatchEvent(new window.Event('change'));await until(window,()=>$('frame-time-label').textContent.startsWith('2.00'));$('frame-time').value=0;$('video-mode').value='sequence';$('period').value=1;$('max-frames').value=4;
 $('locate').click();await until(window,()=>!$('locate').disabled);assert('video has four selectable results',$('frames').options.length===4);report.video=[...$('frames').options].map(o=>o.textContent);
 $('frames').value=2;$('frames').dispatchEvent(new window.Event('change'));await until(window,()=>$('result').textContent.includes('Visual observation rejected'));assert('blank video frame clears pose',$('map-label').textContent.includes('NO ACCEPTED CAMERA POSE'));
 $('frames').value=3;$('frames').dispatchEvent(new window.Event('change'));await until(window,()=>$('map-label').textContent.includes('HYPOTHESIS'));assert('later frame recovers alternatives',!$('hypotheses').disabled);
 document.title='PASS media flow';
 }catch(e){report.error=String(e);document.title='FAIL media flow'}finally{status.textContent=JSON.stringify(report,null,2);await fetch('/__test__/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({media_flow:report})}).catch(()=>{})}};
frame.src='/index.html';
