[package]
name = "navigate-data-fs"
version = "0.1.0"
edition = "2024"
[dependencies]
navigate-data = { path = "../navigate-data" }
tokio = { version = "1", features = ["fs", "rt"] }
[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt", "fs"] }
[lints]
workspace = true
