import assert from 'node:assert/strict';
import {diverseShortlist} from '../webapp/shortlist.js';
const references=[0,10,100].map(x=>({span_m:100,image:{width:640,height:640},world:p=>{assert.deepEqual(p,[319.5,319.5]);return [x,0,10]}}));
const queries=[0,5,90,355].map(angle=>({angle}));
const ranked=[{reference_index:0,query_index:0},{reference_index:1,query_index:1},{reference_index:0,query_index:3},{reference_index:2,query_index:0},{reference_index:0,query_index:2}];
assert.deepEqual(diverseShortlist(ranked,references,queries,3),[ranked[0],ranked[3],ranked[4]]);
assert.deepEqual(diverseShortlist(ranked,references,queries,0),[]);
assert.equal(diverseShortlist(ranked,references,queries,2).length,2);
assert.deepEqual(diverseShortlist(ranked,[{...references[0],world:()=>null}],queries,5),[]);
const scaled=[50,75,100,150,200].map(span_m=>({...references[0],span_m}));
const scaleRanks=scaled.map((_,reference_index)=>({reference_index,query_index:0}));
assert.deepEqual(diverseShortlist(scaleRanks,scaled,queries,5),scaleRanks);
assert.deepEqual(diverseShortlist(scaleRanks,scaled,queries,3),scaleRanks.slice(0,3));
const nearby=[100,110].map(span_m=>({...references[0],span_m}));
assert.deepEqual(diverseShortlist(scaleRanks.slice(0,2),nearby,queries,2),scaleRanks.slice(0,1));
const unknown=[{...references[0],span_m:undefined},{...references[0],span_m:undefined}];
assert.deepEqual(diverseShortlist(scaleRanks.slice(0,2),unknown,queries,2),scaleRanks.slice(0,2));
console.info('Retrieval shortlist preserves geographic, heading and scale diversity within its budget');
