import assert from 'node:assert/strict';
import {refinementFrames,addUnresolvedFrames} from '../webapp/scene-refinement-frames.js';
const frames=Array.from({length:300},(_,i)=>({observation_sha256:String(i),capture_time_ns:i*2e8,sequence:i}));
const before=JSON.stringify(frames),required=['51','107','193'];
const selected=refinementFrames(frames,required,{limit:20});
assert.equal(selected.length,20);assert.equal(selected[0],frames[0]);assert.equal(selected.at(-1),frames.at(-1));
for(const id of required)assert.ok(selected.some(o=>o.observation_sha256===id),'map anchors survive camera subsampling');
assert.equal(new Set(selected.map(o=>o.observation_sha256)).size,20);
assert.equal(JSON.stringify(frames),before);assert.deepEqual(refinementFrames(frames,required,{limit:20}),selected);
const unresolved=frames.filter(o=>!selected.includes(o)).slice(0,8).map(o=>o.observation_sha256);
const retry=addUnresolvedFrames(selected,frames,unresolved,{limit:25});
assert.equal(retry.length,25);for(const o of selected)assert.ok(retry.includes(o));
assert.ok(retry.every(o=>frames.includes(o)),'retry uses real source observations, not interpolated poses');
assert.strictEqual(addUnresolvedFrames(selected,frames,[],{limit:25}),selected);
assert.throws(()=>refinementFrames(frames,['missing'],{limit:20}),/absent/);
assert.throws(()=>refinementFrames([...frames,frames[0]],[],{limit:20}),/repeated/);
assert.throws(()=>refinementFrames(frames,required,{limit:3}),/exceed/);
assert.throws(()=>addUnresolvedFrames(selected,frames,['unknown']),/unknown/);
const stills=frames.slice(0,10).map(o=>({...o,capture_time_ns:0}));
assert.equal(refinementFrames(stills,[],{limit:5}).length,5,'same-time still images retain distributed source coverage');
console.info('Bounded scene selection preserves map anchors and source identities and retries real unresolved frames.');

const {connectRefinementFrames}=await import('../webapp/scene-refinement-frames.js');
const sparse=[frames[0],frames[4],frames[8],frames[12]],point=(...indices)=>({observations:indices.map(camera_index=>({camera_index}))});
const connected=connectRefinementFrames(sparse,frames,[point(0,1),point(2,3)]);
assert.deepEqual(connected.frames,[frames[0],frames[4],frames[6],frames[8],frames[12]]);
assert.deepEqual(connected.disconnected_observation_sha256,['8','12']);
assert.deepEqual(connectRefinementFrames(sparse,frames,[point(0,1,2,3)]).frames,sparse);
assert.deepEqual(connectRefinementFrames(sparse,frames,[point(0,1),point(2,3)],{limit:4}).frames,sparse,'resource bounds preserve an unresolved component');
const adjacent=connectRefinementFrames(frames.slice(0,4),frames,[point(0,1),point(2,3)]);
assert.equal(adjacent.frames.length,4);assert.deepEqual(adjacent.disconnected_observation_sha256,['2','3'],'no invented frame can bridge adjacent unsupported source images');
assert.throws(()=>connectRefinementFrames([...sparse].reverse(),frames,[]),/ordered/);
assert.throws(()=>connectRefinementFrames(sparse,frames,[point(0,4)]),/unknown camera/);
assert.equal(JSON.stringify(frames),before);
console.info('Disconnected support components request real intermediate frames and remain explicit when the budget or source is exhausted.');
