import assert from 'node:assert/strict';
import {cropPlan} from '../webapp/crop-plan.js';
import {matchingOptions} from '../webapp/matching-options.js';
import {cameraForImage} from '../webapp/calibration.js';
const fast=matchingOptions('fast'),detail=matchingOptions('balanced');
const a=cameraForImage(3840,2160,82.1,fast.longEdge),b=cameraForImage(3840,2160,82.1,detail.longEdge);
assert.ok(b.width>a.width);assert.ok(Math.abs(b.fx/a.fx-b.width/a.width)<1e-12);assert.ok(Math.abs(b.fy/a.fy-b.height/a.height)<1e-12);
const plans=cropPlan({width:1024,height:1024,baseSize:1500,center:[512,512],metresPerPixel:.5,radius:500,scales:detail.scales});
assert.equal(new Set(plans.map(p=>p.scale)).size,3);
assert.ok(plans.some(p=>p.x<0&&p.y<0),'a crop larger than the package uses a masked border');
assert.ok(plans.length<=160);
