import assert from 'node:assert/strict';
import {CoverageLoader,viewCoverage} from '../webapp/dynamic-coverage.js';
import {toGlobePose} from '../webapp/geography.js';
const pack={anchor_lat_lon:[40.54,-74.45],tiles:[]};
const pose=toGlobePose(pack,{position_enu_m:[0,0,800],eye_to_enu_xyzw:[0,0,0,1]});
const request=viewCoverage(pack,pose,800);
assert.ok(Math.abs((request.bounds[0]+request.bounds[2])/2+74.45)<1e-6);
assert.ok(Math.abs((request.bounds[1]+request.bounds[3])/2-40.54)<1e-6);
assert.equal(viewCoverage(pack,pose,15e6),null);
let requests=0,downloads=0,attachments=0,remembered=0;
const loader=new CoverageLoader({request:async url=>{requests++;return url.includes('coverage-plan')?{imagery_tiles:[1]}:{status:'complete',region:{manifest:pack}}},download:async()=>downloads++,attach:async()=>attachments++,installed:async()=>[],remember:async()=>remembered++,status:()=>{}});
await loader.update(request);assert.equal(requests,0,'no provider request without enabling dynamic loading');
loader.enabled=true;await Promise.all([loader.update(request),loader.update(request)]);
assert.equal(requests,2);assert.equal(downloads,1);assert.equal(attachments,1);assert.equal(remembered,1);
assert.deepEqual(pack.anchor_lat_lon,[40.54,-74.45]);
const tile={xyz:[16,19214,24677],imagery:{chunk:'test'}},n=2**16;
const lon=(tile.xyz[1]+.5)/n*360-180,lat=Math.atan(Math.sinh(Math.PI*(1-2*(tile.xyz[2]+.5)/n)))*180/Math.PI;
const cached={...pack,tiles:[tile]};let cachedAttachments=0;
const cachedLoader=new CoverageLoader({request:()=>{throw Error('Unexpected provider request')},download:async()=>{},attach:async p=>{assert.equal(p,cached);cachedAttachments++},installed:async()=>[],available:async()=>[cached],remember:async()=>{},status:()=>{}});
cachedLoader.enabled=true;await cachedLoader.update({bounds:[lon-.00001,lat-.00001,lon+.00001,lat+.00001],zoom:16});
assert.equal(cachedAttachments,1,'stored packages are reused without provider access');
