import assert from 'node:assert/strict';
import {PipelineSession} from '../webapp/pipeline-session.js';
const created=[];
const sessions=new PipelineSession(()=>{const p={loads:0,closes:0,initialize:async()=>{p.loads++},close:()=>{p.closes++}};created.push(p);return p});
const pack={pack_id:'one'},camera={width:960,height:544},options={keypoints:1024};
const first=await sessions.acquire(pack,camera,options,()=>{});
assert.equal(await sessions.acquire({...pack},{...camera},{...options},()=>{}),first);
assert.equal(first.loads,1,'a second observation retains model sessions and reference features');
const second=await sessions.acquire({pack_id:'two'},camera,options,()=>{});
assert.notEqual(second,first);assert.equal(first.closes,1,'a different map releases the previous worker');
await sessions.acquire({pack_id:'two'},{...camera,fx:680},options,()=>{});assert.equal(second.closes,1);
const calibrated=sessions.current;
await sessions.acquire({pack_id:'two'},{...camera,fx:680},{keypoints:2048},()=>{});assert.equal(calibrated.closes,1);
const active=sessions.current;sessions.close();sessions.close();assert.equal(active.closes,1);
assert.notEqual(await sessions.acquire(pack,camera,options,()=>{}),active,'cancelled workers are never reused');
sessions.close();
let failedClosed=0;
const failed=new PipelineSession(()=>({initialize:async()=>{throw Error('device lost')},close:()=>{failedClosed++}}));
await assert.rejects(failed.acquire(pack,camera,options,()=>{}),/device lost/);assert.equal(failed.current,null);assert.equal(failedClosed,1);
console.info('Resident pipeline reuse, compatibility changes, cancellation and initialization failure passed');
let complete,initializations=0;
const loading=new PipelineSession(()=>({initialize:()=>{initializations++;return new Promise(resolve=>{complete=resolve})},close(){}}));
let returned=false;
const waiting=loading.acquire(pack,camera,options,()=>{});
const sharing=loading.acquire(pack,camera,options,()=>{}).then(value=>{returned=true;return value});
await Promise.resolve();assert.equal(returned,false,'a reused worker must finish initialization before inference');assert.equal(initializations,1);
complete();assert.equal(await waiting,await sharing);loading.close();
const cancelled=loading.acquire(pack,camera,options,()=>{});loading.close();complete();await assert.rejects(cancelled,{name:'AbortError'});
console.info('Concurrent initialization and cancellation during loading passed');
