import assert from 'node:assert/strict';
import {TrackSelection} from '../webapp/track-selection.js';
import {connectedSamples} from '../webapp/pose-playback.js';
const pose=x=>({tracking_supported:true,track_id:'track',map_manifest_sha256:'map',position_enu_m:[x,0,100],eye_to_enu_xyzw:[0,0,0,1]});
const sample=(time,x)=>({time,h:x===null?null:pose(x),frame:{observation_sha256:String(time)}});
const a=[sample(0,0),sample(1,1),sample(2,null),sample(3,null),sample(4,4)];
const b=[sample(0,20),sample(1,21),sample(2,22),sample(3,23),sample(4,24)];
const branches=new Map([['a',a],['b',b]]),saved=JSON.stringify([...branches]),selection=new TrackSelection();
const selected=selection.choose(branches,'a',1.1);
assert.deepEqual(selected.get('a').map(s=>s.h?.position_enu_m[0]??null),[0,1,null,null,4]);
assert.equal(selected.has('b'),false,'an unrelated path cannot fill gaps in the selected path');
assert.strictEqual(selected.get('a'),a,'the complete selected branch retains its unsupported gaps');
assert.ok(connectedSamples(selected.get('a')[0],selected.get('a')[1],{maxGap:1.1}));
assert.equal(connectedSamples(selected.get('a')[1],selected.get('a')[4],{maxGap:1.1}),false,'selection cannot join a gap');
assert.strictEqual(selection.choose(branches,'a',1.1),selected,'unchanged selection reuses the display cache');
const other=selection.choose(branches,'b',1.1);assert.deepEqual([...other.keys()],['b']);assert.strictEqual(other.get('b')[2],b[2]);
assert.equal(JSON.stringify([...branches]),saved,'selection preserves every pose, identity, and alternative');
const parent=sample(0,1),alias={...parent,source_h:parent.h,h:{...parent.h}},child=sample(1,2);
const aliases=new Map([['anchor',[parent]],['continuation',[alias,child]]]);
assert.deepEqual([...selection.choose(aliases,'anchor',1.1).keys()],['continuation'],'the selected anchor uses its exact connected display copy');
const empty=new Map([['missing',[sample(0,null)]]]);assert.equal(selection.choose(empty,'missing',1.1).size,0,'unsupported observations do not acquire a path');
console.info('Review selection displays one path, preserves alternatives, reuses caches, and does not bridge gaps');
