import assert from 'node:assert/strict';
import {TemporalSearch,poseConverged,refineCandidates} from '../webapp/temporal-search.js';
const pose=(x,q=[0,0,0,1])=>({position_enu_m:[x,0,110],eye_to_enu_xyzw:q});
const history=new TemporalSearch();
const first={observation_sha256:'first',candidate_hypotheses:[{candidate_id:2,accepted:true,...pose(0)},{candidate_id:9,accepted:true,...pose(80)},{candidate_id:10,accepted:false,...pose(1)}]};
history.remember(first);first.candidate_hypotheses[0].position_enu_m[0]=999;
assert.deepEqual(history.seeds('second',[0,0,110],100).map(x=>x.position_enu_m[0]),[0,80],'separate alternatives survive without averaging');
assert.deepEqual(history.seeds('first',[0,0,110],100),[],'reprocessing does not seed itself');
assert.deepEqual(history.seeds('second',[1000,0,110],100),[],'out-of-prior seeds do not replace an area search');
const seeds=history.seeds('second',[0,0,110],100);
const tracked=history.label({observation_sha256:'second',accepted:true,decision:'unique_among_evaluated',candidate_hypotheses:[{candidate_id:0,accepted:true,...pose(2)}]},seeds);
assert.equal(tracked.accepted,false);assert.equal(tracked.decision,'unresolved');assert.equal(tracked.search_seeds.observation_sha256,'first');assert.deepEqual(tracked.search_seeds.candidate_ids,[2,9]);
assert.match(tracked.evidence_correlation,/unknown/);
assert.equal(poseConverged(pose(0),pose(.01,[0,0,0,-1])),true);
assert.equal(poseConverged(pose(0),pose(.2)),false);
assert.equal(poseConverged(pose(0),pose(0,[0,0,Math.sin(.1),Math.cos(.1)])),false);
const rendered=[],matched=[],reports=new Map();
const renderer={
 render_reference:async(id,json)=>{rendered.push({id,pose:JSON.parse(json)});return new Uint8Array([1])},
 refine:(id,_pairs,backend)=>{assert.equal(backend,'replacement-matcher');const latest=id===0?{candidate_id:id,accepted:true,...pose(.01)}:{candidate_id:id,accepted:false,reason:'current image has insufficient geometry'};reports.set(id,latest);return JSON.stringify(latest)},
 select:()=>JSON.stringify({candidate_hypotheses:[...reports.values()]})
};
const matcher={matchImages:async(_reference,query,keys)=>{matched.push({query,keys});return {pairs:[],backend_identity:'replacement-matcher'}}};
const query={gray:new Uint8Array([7])};
const result=await refineCandidates(renderer,matcher,{width:1,height:1},seeds,query,'second',3,()=>{});
assert.equal(rendered.length,2,'converged and rejected candidates each stop without extra fits');
assert.deepEqual(result.candidate_hypotheses.map(h=>h.accepted),[true,false]);
assert.ok(matched.every(m=>m.query===query&&m.keys.query==='second/query'),'every seed is checked using the current observation');
history.remember({observation_sha256:'failed',candidate_hypotheses:[{accepted:false}]});assert.deepEqual(history.seeds('next',[0,0,110],100),[],'a failed observation clears stale tracking seeds');
console.info('Temporal alternatives, seed provenance, current-image verification and convergence passed');
let evaluations=0;const attempts=[];
const refining={render_reference:async(id,json)=>{attempts.push(JSON.parse(json));return new Uint8Array([1])},refine:()=>JSON.stringify(++evaluations===1?{accepted:false,refinement_proposal:pose(3)}:{accepted:true,...pose(3.01)}),select:()=>JSON.stringify({candidate_hypotheses:[{accepted:evaluations===2}]})};
const recovered=await refineCandidates(refining,matcher,{width:1,height:1},[pose(0)],query,'same-observation',3,()=>{});
assert.equal(evaluations,2);assert.deepEqual(attempts.map(p=>p.position_enu_m[0]),[0,3]);assert.equal(recovered.candidate_hypotheses[0].accepted,true);
evaluations=0;const stillRejected=await refineCandidates(refining,matcher,{width:1,height:1},[pose(0)],query,'same-observation',1,()=>{});assert.equal(stillRejected.candidate_hypotheses[0].accepted,false,'a pending refinement proposal is never accepted by itself');
console.info('Rejected surface seeds require a new render and a new full acceptance check');
const tracking=new TemporalSearch(),pixels={gray:new Uint8Array([1,2,3,4]),width:2,height:2};
tracking.remember({...first,sequence:4,capture_time_ns:100},pixels);
pixels.gray.fill(0);
const tracks=[];
const tracker={render_reference:async(id,json)=>{tracks.push({id,pose:JSON.parse(json)});return new Uint8Array(4)},
 track:(previous,json,_pairs,backend)=>{assert.equal(previous[0],1,'retain the previous camera pixels');assert.equal(backend,'replacement-matcher');const metadata=JSON.parse(json);assert.equal(metadata.sequence,4);assert.equal(metadata.capture_time_ns,100);return JSON.stringify({candidate_id:metadata.candidate_id,accepted:false,tracking_supported:true,...pose(metadata.candidate_id*80+3)})},
 select:()=>JSON.stringify({observation_sha256:'next',sequence:5,capture_time_ns:200,accepted:false,decision:'rejected'})};
const allSeeds=tracking.seeds('next',[500,0,110],1000);
const relative=await tracking.track(tracker,matcher,{width:2,height:2},allSeeds,query,'next',()=>{});
assert.equal(relative.accepted,false);assert.equal(relative.decision,'relative_tracking');
assert.equal(relative.candidate_hypotheses.length,2,'do not collapse initial map alternatives');
assert.ok(relative.candidate_hypotheses.every(h=>!h.accepted&&h.tracking_supported&&!h.geometry_covariance));
assert.deepEqual(relative.candidate_hypotheses.map(h=>h.tracking_anchor.candidate_id),[2,9]);
tracking.remember(relative,pixels);assert.equal(tracking.previous.steps,1);
assert.equal(tracking.previous.candidates[0].tracking_anchor.observation_sha256,'first','relative tracking retains its original map anchor');
tracker.track=()=>JSON.stringify({accepted:false,tracking_supported:false});
assert.equal(await tracking.track(tracker,matcher,{width:2,height:2},allSeeds,query,'failed',()=>{}),null,'failed relative geometry requires map verification or a new search');
console.info('Relative tracking retains alternatives and anchor identity without producing independent map acceptance');
let variants=0;
const alternateMatcher={...matcher,async *matchAlternatives(){variants++;yield {pairs:[],backend_identity:'rotated-camera-adapter'}}};
tracker.track=(_pixels,metadata,_pairs,backend)=>JSON.stringify({candidate_id:JSON.parse(metadata).candidate_id,accepted:false,tracking_supported:backend==='rotated-camera-adapter',...pose(3)});
const turned=await tracking.track(tracker,alternateMatcher,{width:2,height:2},allSeeds,query,'turned',()=>{});
assert.equal(variants,1);assert.equal(turned.decision,'relative_tracking');assert.equal(turned.accepted,false);
assert.ok(turned.candidate_hypotheses.every(h=>h.tracking_supported));
assert.equal(turned.candidate_hypotheses[0].tracking_anchor.observation_sha256,'first');
console.info('Adapter alternatives require a fresh geometric check and retain the same anchor');
const progressEvents=[];
const loadingMatcher={matchImages:async(_reference,_query,keys)=>{keys.progress('Loading model for this observation');return {pairs:[],backend_identity:'replacement-matcher'}}};
await refineCandidates(renderer,loadingMatcher,{width:1,height:1},[pose(0)],query,'new-request',1,text=>progressEvents.push(text));
assert.ok(progressEvents.includes('Loading model for this observation'),'lazy model progress belongs to the active observation, not the completed initialization request');

const lineage=relative.candidate_hypotheses[0].track_id;
assert.equal(typeof lineage,'string');
const seedsForCheck=relative.candidate_hypotheses.filter(h=>h.tracking_supported);
const restarted=tracking.label({observation_sha256:'map-update',candidate_hypotheses:[{candidate_id:0,accepted:true,...pose(7)}]},seedsForCheck,relative);
const updated=restarted.candidate_hypotheses[0];
assert.equal(updated.track_id,lineage);assert.equal(updated.continuity_break,true);
assert.deepEqual(updated.relative_alternative,relative.candidate_hypotheses[0],'a supported relative alternative is retained at a map restart');
tracking.remember(restarted,pixels);
assert.equal(tracking.previous.candidates[0].track_id,lineage);
assert.equal(tracking.previous.candidates[0].tracking_anchor.observation_sha256,'map-update','map evidence identity changes while the camera path lineage stays traceable');

const refreshing=new TemporalSearch();
assert.equal(refreshing.regionalDue(0),true);
const anchor={observation_sha256:'anchor',capture_time_ns:0,sequence:0,decision:'unique_among_evaluated',candidate_hypotheses:[{candidate_id:0,accepted:true,...pose(0)}]};
refreshing.remember(anchor,pixels,{regional:true});
assert.equal(refreshing.regionalDue(4.9e9),false);
assert.equal(refreshing.regionalDue(5e9),true);
refreshing.remember({...anchor,capture_time_ns:4e9,observation_sha256:'local-check'},pixels);
assert.equal(refreshing.regionalDue(5e9),true,'local map checks cannot postpone a regional search');
const continuation={...relative,capture_time_ns:5e9,sequence:25,candidate_hypotheses:[relative.candidate_hypotheses[0]]};
const regional={...anchor,observation_sha256:'regional',capture_time_ns:5e9,candidate_hypotheses:[{candidate_id:2,accepted:true,...pose(80)}]};
const resumed=refreshing.reacquired(regional,continuation);
assert.equal(resumed.candidate_hypotheses[0].track_id,continuation.candidate_hypotheses[0].track_id,'one camera path can restart without blending poses');
assert.equal(resumed.candidate_hypotheses[0].continuity_break,true);
assert.deepEqual(resumed.candidate_hypotheses[0].position_enu_m,[80,0,110]);
assert.deepEqual(resumed.regional_search.relative_alternatives,continuation.candidate_hypotheses);
const ambiguous=refreshing.reacquired({...regional,candidate_hypotheses:[...regional.candidate_hypotheses,{candidate_id:3,accepted:true,...pose(200)}]},continuation);
assert.equal(ambiguous.candidate_hypotheses.length,2);
assert.ok(ambiguous.candidate_hypotheses.every(h=>h.track_id===undefined),'ambiguous candidates do not inherit a selected lineage');
const rejected={...regional,decision:'rejected',candidate_hypotheses:[{accepted:false,reason:'No valid depth'}]};
const conditional=refreshing.reacquired(rejected,continuation);
assert.equal(conditional.accepted,false);
assert.equal(conditional.decision,'relative_tracking');
assert.deepEqual(conditional.regional_search.candidate_hypotheses,rejected.candidate_hypotheses);
refreshing.remember(conditional,pixels,{regional:true});
assert.equal(refreshing.regionalDue(9e9),false);
assert.equal(refreshing.regionalDue(10e9),true);
assert.equal(refreshing.regionalDue(3e9),true,'backward timestamps cannot reuse a later search');
console.info('Timed geographic refresh preserves map alternatives and conditional tracking without false fusion');

for(const invalid of [0,-1,NaN,Infinity])assert.throws(()=>refreshing.regionalDue(0,invalid),/interval/);

assert.ok(matched.slice(0,2).every(m=>m.keys.stage==='refinement'));

const branchSeeds=[{candidate_id:2,track_id:'path-a',...pose(0)},{candidate_id:9,track_id:'path-b',...pose(80)}];
const branchRelative={observation_sha256:'current',capture_time_ns:8e9,sequence:8,accepted:false,decision:'relative_tracking',candidate_hypotheses:branchSeeds.map(seed=>({...seed,accepted:false,tracking_supported:true,tracking_anchor:{observation_sha256:'map-anchor',candidate_id:seed.candidate_id,map_manifest_sha256:'m'}}))};
const mixedMap={observation_sha256:'current',capture_time_ns:8e9,sequence:8,accepted:true,candidate_hypotheses:[{candidate_id:0,accepted:true,...pose(3)},{candidate_id:1,accepted:false,reason:'No map image support'}]};
const branchUpdate=tracking.label(mixedMap,branchSeeds,branchRelative);
assert.equal(branchUpdate.accepted,false);assert.equal(branchUpdate.decision,'unresolved');assert.deepEqual(branchUpdate.unresolved_candidate_ids,[0,1]);
assert.equal(branchUpdate.candidate_hypotheses[0].accepted,true);
const surviving=branchUpdate.candidate_hypotheses[1];
assert.equal(surviving.accepted,false);assert.equal(surviving.tracking_supported,true);
assert.equal(surviving.candidate_id,1,'the report uses distinct observation-local candidate IDs');
assert.equal(surviving.parent_candidate_id,9);assert.equal(surviving.track_id,'path-b');
assert.deepEqual(surviving.position_enu_m,[80,0,110]);
assert.deepEqual(surviving.tracking_anchor,branchRelative.candidate_hypotheses[1].tracking_anchor);
assert.equal(surviving.local_map_attempt.reason,'No map image support');
assert.equal(surviving.continuity_break,undefined,'a failed map attempt does not restart a supported relative branch');
tracking.remember(branchUpdate,pixels,{map:true});
assert.deepEqual(tracking.seeds('later',[0,0,110],100).map(h=>h.position_enu_m[0]),[3,80],'both geographic alternatives remain available for the next observation');
assert.deepEqual(branchRelative.candidate_hypotheses.map(h=>h.position_enu_m[0]),[0,80],'the update does not move or combine the original relative proposals');
console.info('Failed local map checks preserve other supported relative branches, lineage, and rejection evidence');
