import assert from 'node:assert/strict';
import {detectorInput,decodeDetector,decodeAssignments,suppress} from '../webapp/qa-superpoint-decode.js';
const image={width:80,height:40,gray:new Uint8Array(3200).fill(255)},input=detectorInput(image,64,64);
assert.equal(input.data[0],0);assert.equal(input.data[32*64+32],1);
assert.ok(Math.abs(input.pixel([31.5,31.5])[0]-39.5)<1e-10);
assert.ok(Math.abs(input.pixel([31.5,31.5])[1]-19.5)<1e-10);
const small={width:32,height:32,gray:new Uint8Array(1024)},fixed=detectorInput(small,32,32),logits=new Float32Array(65*16),descriptors=new Float32Array(256*16);
logits.fill(20,64*16);descriptors.fill(1,0,16);
for(const [x,y,score] of [[8,8,25],[10,8,23],[22,22,24]])logits[(y%8*8+x%8)*16+Math.floor(y/8)*4+Math.floor(x/8)]=score;
const output={scores:{dims:[1,65,4,4],data:logits},descriptors:{dims:[1,256,4,4],data:descriptors}};
const features=decodeDetector(output,small,fixed,1024);
assert.deepEqual(features.pixels,[[22,22],[8,8]]);
assert.deepEqual([...features.points],[22,22,8,8]);
assert.equal(features.descriptors[0],1);assert.equal(features.descriptors[1],0);
assert.deepEqual(decodeDetector(output,small,fixed,1).pixels,[[22,22]]);
const valid=new Uint8Array(1024).fill(255);valid[8*32+8]=0;
assert.deepEqual(decodeDetector(output,{...small,valid},fixed).pixels,[[22,22]]);
const first={pixels:[[1,2],[3,4]]},second={pixels:[[5,6],[7,8]]};
assert.deepEqual(decodeAssignments(new BigInt64Array([1n,-1n]),first,second),[{reference:[1,2],query:[7,8]}]);
for(const ids of [[0n,0n],[2n,-1n],[-2n,-1n]])assert.throws(()=>decodeAssignments(ids,first,second),/Invalid LightGlue assignment/);
assert.throws(()=>decodeAssignments([],first,second),/count differs/);
assert.throws(()=>decodeDetector({...output,scores:{...output.scores,dims:[1,64,4,4]}},small,fixed),/Invalid SuperPoint output/);
assert.deepEqual([...suppress(new Float32Array(64),8,8)],Array(64).fill(0));
console.info('Research decoder checks image coordinates, padding, suppression, normalization, validity and assignment failures');
